"""Build actual GAFF2 solvent and PMMA/rigid-graphene exploratory systems.

Solvent parameters generated by AmberTools; PMMA from published SI S2;
graphene LJ from SI S1. Lorentz-Berthelot cross interactions are assumptions
to validate. Rigid graphene cannot predict damage or oxide delamination.
"""
from pathlib import Path
import argparse,json,re,itertools,subprocess,time
import numpy as np
from scipy.spatial.transform import Rotation
from ase import Atoms
from ase.io import read,write
from pmma_topology import export as pmma_export

HERE=Path(__file__).resolve().parent
PACKMOL=str(HERE/'amber-env/bin/packmol')
ROOT=HERE/'results/gaff-systems'
RHO={'HFIP':1.607,'DMF':.944,'THF':.884,'AceticAcid':1.045,'Anisole':.99}
RES={'HFIP':'HFI','DMF':'DMF','THF':'THF','AceticAcid':'ACE','Anisole':'ANI'}

def split_topology(name):
    text=(HERE/'results/gaff2'/name/'molecule.top').read_text()
    begin=text.index('[ atomtypes ]');middle=text.index('[ moleculetype ]')
    end=text.index('[ system ]')
    defaults=text[text.index('[ defaults ]'):begin]
    assert re.search(r'\b1\s+2\s+yes\s+0\.5\s+0\.83333333',defaults)
    atoms=[]
    local=text[middle:end]
    in_atoms=False
    for line in local.splitlines():
        if line.strip().startswith('['):in_atoms=line.strip()=='[ atoms ]';continue
        if in_atoms and line.strip() and not line.lstrip().startswith(';'):
            t=line.split();atoms.append(dict(name=t[4],mass=float(t[7]),charge=float(t[6])))
    return text[begin:middle],local,atoms

def graphene(nx=8,ny=14,a=.1418):
    lx=3*a*nx;ly=np.sqrt(3)*a*ny
    unit=np.array([[0,0,0],[a,0,0],[1.5*a,np.sqrt(3)*a/2,0],
                   [2.5*a,np.sqrt(3)*a/2,0]])
    xyz=np.concatenate([unit+[i*3*a,j*np.sqrt(3)*a,0]
                        for i,j in itertools.product(range(nx),range(ny))])
    delta=xyz[:,None,:]-xyz[None,:,:]
    delta[:,:,0]-=np.rint(delta[:,:,0]/lx)*lx
    delta[:,:,1]-=np.rint(delta[:,:,1]/ly)*ly
    distances=np.linalg.norm(delta,axis=2)
    assert np.all(((distances>.13)&(distances<.15)).sum(axis=1)==3)
    return xyz,lx,ly

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--solvent',choices=list(RHO),default='HFIP')
    parser.add_argument('--polymer-n',type=int,default=0);parser.add_argument('--seed',type=int,default=20261006)
    parser.add_argument('--packing-tolerance-A',type=float,default=2.0)
    parser.add_argument('--periodic-pack',action='store_true',help='Pack over the full periodic cell, with distances to periodic images checked')
    parser.add_argument('--bulk-molecules',type=int,default=125)
    args=parser.parse_args();name=args.solvent;n=args.polymer_n
    assert 1.5 <= args.packing_tolerance_A <= 2.5
    assert args.bulk_molecules >= 64 or n, 'The1nmcutoffneeds a sufficiently large liquid cell'
    suffix=f'_N{args.bulk_molecules}' if not n and args.bulk_molecules!=125 else ''
    out=ROOT/(f'{name}_n{n}_seed{args.seed}'+suffix);out.mkdir(parents=True,exist_ok=True)
    if (out/'system.top').exists():raise RuntimeError('Existing prepared system preserved')
    types,solvent_itp,atoms=split_topology(name);mass=sum(x['mass'] for x in atoms);nsat=len(atoms)
    top=['; Generated comparator GAFF2; no surface-desorption qualification',
         '[ defaults ]','1 2 yes 0.5 0.83333333',types]
    a=read(HERE/'results/clusters'/f'{name}.refined.xyz')
    ng=0;npma=0;pma_names=[]
    if n:
        g,lx,ly=graphene();lz=3.8;g[:,2]=lz/2;ng=len(g)
        poly=pmma_export(n,args.seed);b=read(poly/'initial.xyz');npma=len(b)
        position=b.positions*.1;position-=position.mean(axis=0)
        _,_,vh=np.linalg.svd(position,full_matrices=False)
        position=position@vh.T
        dz=max(.65,-float(position[:,2].min())+.26)
        position+=[lx/2,ly/2,lz/2+dz];b.positions=position*10
        write(out/'polymer.xyz',b);write(out/'graphene.xyz',Atoms('C'+str(ng),positions=g*10))
        top+=['[ atomtypes ]','GR 6 12.011 0 A 0.3470 0.2750',
              (poly/'atomtypes.itp').read_text().replace('[ atomtypes ]',''),
              '; Rigid sheet self-interactions are constant: omit G-G LJ only.',
              '[ nonbond_params ]','GR GR 1 0.3470 0.0',
              '[ moleculetype ]','GRAPHENE 0','[ atoms ]']
        for i in range(1,ng+1):top.append(f'{i} GR 1 GR C{i} {i} 0.0 12.011')
        pma=(poly/'pmma.itp').read_text();top.append(pma)
        # Read exact polymer atom order and masses from the prepared ITP.
        flag=False;pmass=0
        for line in pma.splitlines():
            if line.strip().startswith('['):flag=line.strip()=='[ atoms ]';continue
            if flag and line.strip() and not line.startswith(';'):
                t=line.split();pma_names.append(t[4]);pmass+=float(t[7])
        assert len(pma_names)==npma
        volume=lx*ly*(lz-.4)-pmass/(602.214076*1.18)
        nmol=int(round(RHO[name]*602.214076*volume/mass))
        fixed=f'''structure graphene.xyz
  number 1
  fixed 0 0 0 0 0 0
end structure
structure polymer.xyz
  number 1
  fixed 0 0 0 0 0 0
end structure
'''
        # Packmol outside-box applies each axis separately; with inside x/y
        # that can contradict the constraints. Use two explicit compartments.
        lower_volume=lx*ly*(lz-.4)/2
        lower_count=int(round(nmol*lower_volume/volume))
        solvent_blocks=f'''structure solvent.xyz
  number {lower_count}
  inside box 1.0 1.0 1.0 {lx*10-1:.6f} {ly*10-1:.6f} {(lz/2-.20)*10:.6f}
end structure
structure solvent.xyz
  number {nmol-lower_count}
  inside box 1.0 1.0 {(lz/2+.20)*10:.6f} {lx*10-1:.6f} {ly*10-1:.6f} {lz*10-1:.6f}
end structure
'''
    else:
        nmol=args.bulk_molecules;lx=ly=lz=(nmol*mass/(602.214076*.8))**(1/3)
        fixed='';volume=lx*ly*lz
        solvent_blocks=f'''structure solvent.xyz
  number {nmol}
  inside box 1.0 1.0 1.0 {lx*10-1:.6f} {ly*10-1:.6f} {lz*10-1:.6f}
end structure
'''
    top +=[solvent_itp,'[ system ]',f'{name} comparator n{n}',
           '[ molecules ]']
    if n:top+=['GRAPHENE 1','PMMA 1']
    top.append(f'{RES[name]} {nmol}')
    (out/'system.top').write_text('\n'.join(top)+'\n')
    write(out/'solvent.xyz',a)
    if args.periodic_pack:
        # No artificial empty margin at the simulation-cell faces. Graphene
        # and polymer are fixed, and PackMol handles exclusions to them.
        solvent_blocks=f'''structure solvent.xyz
  number {nmol}
end structure
'''
    periodic=f'pbc {lx*10:.9f} {ly*10:.9f} {lz*10:.9f}\n' if args.periodic_pack else ''
    pack=f'''tolerance {args.packing_tolerance_A:.6f}
filetype xyz
output packed.xyz
seed {args.seed}
nloop 500
{periodic}{fixed}{solvent_blocks}
'''
    (out/'packmol.in').write_text(pack)
    with (out/'packmol.in').open() as inp,(out/'packmol.log').open('w') as log:
        r=subprocess.run([PACKMOL],stdin=inp,stdout=log,stderr=subprocess.STDOUT,cwd=out,timeout=120)
    if r.returncode:raise RuntimeError('Packing failed')
    allatoms=read(out/'packed.xyz');total=ng+npma+nmol*nsat
    assert len(allatoms)==total
    positions=allatoms.positions*.1
    # GRO has a strict20-column prefix; variable coordinate width is read
    # from decimal positions. Use9decimals to preserve the molecular geometry.
    gro=[f'{name} n{n} comparator',f'{total:5d}']
    meta=[]
    if n:
        meta += [(1,'GR',f'C{i+1}') for i in range(ng)]
        meta += [(2,'PMMA',p) for p in pma_names]
    for j in range(nmol):meta += [(j+3 if n else j+1,RES[name],x['name']) for x in atoms]
    for i,((res,rt,at),xyz) in enumerate(zip(meta,positions),1):
        gro.append(f'{res:5d}{rt:<5s}{at:>5s}{i:5d}{xyz[0]:14.9f}{xyz[1]:14.9f}{xyz[2]:14.9f}')
    gro.append(f'{lx:15.9f}{ly:15.9f}{lz:15.9f}')
    (out/'initial.gro').write_text('\n'.join(gro)+'\n')
    def index_lines(values):
        values=list(values)
        return [' '.join(map(str,values[j:j+15])) for j in range(0,len(values),15)]
    index=['[ System ]']+index_lines(range(1,total+1))
    if n:
        index+=['[ GRAPHENE ]']+index_lines(range(1,ng+1))
        index+=['[ PMMA ]']+index_lines(range(ng+1,ng+npma+1))
        index+=['[ Mobile ]']+index_lines(range(ng+1,total+1))
        index+=['[ SOLVENT ]']+index_lines(range(ng+npma+1,total+1))
    (out/'index.ndx').write_text('\n'.join(index)+'\n')
    common='''cutoff-scheme = Verlet
nstlist = 20
rlist = 1.0
coulombtype = PME
rcoulomb = 1.0
vdwtype = Cut-off
rvdw = 1.0
DispCorr = EnerPres
pbc = xyz
fourierspacing = 0.12
ewald-rtol = 1e-4
pme-order = 4
constraints = h-bonds
constraint-algorithm = lincs
lincs-order = 6
lincs-iter = 2
'''
    if n:common+='freezegrps = GRAPHENE\nfreezedim = Y Y Y\n'
    (out/'min.mdp').write_text(common+'integrator = steep\nnsteps = 5000\nemtol = 500\nemstep = 0.005\nnstenergy = 100\n')
    dynamic=common+f'''integrator = md
dt = 0.001
tcoupl = v-rescale
tc-grps = System
tau-t = 0.2
ref-t = 298.15
nstenergy = 1000
nstlog = 1000
nstxout-compressed = 1000
compressed-x-precision = 10000
gen-seed = {args.seed}
'''
    if n:dynamic+='comm-mode = None\n'
    (out/'nvt.mdp').write_text(dynamic+'nsteps = 50000\npcoupl = no\ngen-vel = yes\ngen-temp = 298.15\n')
    (out/'production.mdp').write_text(dynamic+('nsteps = 100000\npcoupl = no\n' if n else
        'nsteps = 500000\npcoupl = C-rescale\npcoupltype = isotropic\ntau-p = 2.0\nref-p = 1.0\ncompressibility = 4.5e-5\n')+
        'gen-vel = no\ncontinuation = yes\n')
    manifest=dict(solvent=name,solvent_model='GAFF2/AM1-BCC from AmberTools26',
                  polymer_n=n,polymer_atoms=npma,graphene_atoms=ng,solvent_molecules=nmol,
                  total_atoms=total,box_nm=[lx,ly,lz],seed=args.seed,
                  packing_tolerance_A=args.packing_tolerance_A,
                  periodic_packing=args.periodic_pack,
                  liquid_number_chosen_using_density_g_cm3=RHO[name],
                  target_density_reference='HFIP1.607 primaryCasoria; DMF/THF nominal25C initialization estimates, not fitted acceptance values',
                  solvent_molar_mass_g_mol=mass,
                  polymer_model='Published2021 SI, documented end caps and1-4 assumption' if n else None,
                  graphene_model='Rigid periodic sheet; LJ SI2021 S1; G-G constant omitted' if n else None,
                  scope=('Exploratory top-face polymer/liquid model; not950K, not SiO2 selectivity, not graphene damage.'
                         if n else 'Neat-solvent liquid model; bulk validation only, no graphene interface.'),
                  forcefield_desorption_qualified=False)
    (out/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
    print(out,manifest,flush=True)

if __name__=='__main__':main()
